seed: 2023
distributed: True
train_visualization_iter: 100


datasets:
  train:
    name: colorization
    dataroot_gt: .data/DAVIS_train/GT
    dataroot_lq: ./data/DAVIS_train/GT
    is_train: true
    num_frame: 15
    interval_length: 9
    gt_size: [240, 432]
    scale: 1
    interval_list: [1]
    random_reverse: true
    use_flip: true
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    normalizing: true


  val:
#    name: REDS4
    name: colorization
    type: Film_color_test_dataset
    dataroot_gt: ./data/DAVIS_test/GT
    dataroot_lq: ./data/DAVIS_test/GT
    is_train: false
    interval_length: 13
    gt_size: [240, 432]
    crop_size: [60, 108]
    scale: 1
    interval_list: [1]
    random_reverse: false
    use_flip: false
    use_rot: false
    normalizing: true


path:
  pretrain_network_g: ./pretrained_models/DeepEnhancer/models/color.pth
  strict_load_g: true
  resume_state: ~
  root: ./DeepEnhancer

trainer:
  lr: !!float 5e-5
  flow_lr_mul: 0.125
  fix_flow: 5000
  gan_lr: !!float 5e-5
  beta1: 0.9
  beta2: 0.99

  G_adv_loss_weight: 0.01
  D_adv_loss_weight: 1.0
  pix_loss_weight: 1.0
  flow_loss_weight: 1.0
  perceptual_loss_weight: 1.0

  optim_g:
    type: Adam
    lr: !!float 5e-5
    weight_decay: 0
    betas: [ 0.9, 0.99 ]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [ 20000, 20000, 20000, 20000, 20000]
    restart_weights: [ 1, 0.5, 0.5, 0.5, 0.5 ]
    eta_min: !!float 1e-7
  reset_periods: true
  total_iter: 100000
  warmup_iter: -1  # no warm up


logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: false


val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      # crop_border: 0
      # test_y_channel: false
    ssim:
      type: calculate_ssim
      # crop_border: 0
      # test_y_channel: false
